ALTER TABLE "AppSetting" ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "MoneyMovement" ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "SavingTransaction" ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "SavingTransactionIncomeSource" ALTER COLUMN "id" DROP DEFAULT;
